IWFF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/',include('usuario.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from . import views
from django.urls import path
app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('agregar_home/<int:producto_id>/', views.agregar_home, name="agregar_home"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"), 
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"), 
    path('limpiar/', views.limpiar_carro, name="limpiar"), 
    path('limpiar_producto/', views.limpiar_carro_producto, name="limpiar_producto"), 
]

core/urls.py
from collections import namedtuple
from django.urls import path
from django.urls.conf import include
from .views import *    
from django.contrib import admin

urlpatterns = [
    #Home
    path('',home, name='home'), 
    #contacto
    path('contacto/', contacto, name="contacto"),
    #producto
    path('agregarproducto/', agregar_producto, name="agregar_producto"),
    path('listarproducto/', listar_productos, name="listar_producto"),
    path('modificarproducto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminarproducto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('categoria/<familia_id>',nombre_familia,name='nombre_familia'),
    #registro
    path('register/', register, name="register"),
    #familia
    path('listar_familias/', listar_familias, name='listar_familias' ),
    path('nueva_familia/', nueva_familia, name='nueva_familia'),
    path('modificarfamilia/<id>/', modificar_familia, name="modificar_familia"),
    path('eliminarfamilia/<id>/', eliminar_familia, name="eliminar_familia"),
    #Factura
    path('listar_factura/', listar_factura,name='listar_factura'),
    path('nueva_factura/', nueva_factura, name='nueva_factura'),
    path('modificarfactura/<id>/', modificar_factura,name='modificar_factura'),
    path('eliminarfactura/<id>/',eliminar_factura,name='eliminar_factura'),
    #Boleta
    path('listar_boleta/', listar_boleta,name='listar_boleta'),
    path('nueva_boleta/', nueva_boleta, name='nueva_boleta'),
    path('modificarboleta/<id>/', modificar_boleta,name='modificar_boleta'),
    path('eliminarboleta/<id>/',eliminar_boleta,name='eliminar_boleta'),
    #Proveedor
    path('listar_proveedor/', listar_proveedor, name='listar_proveedor' ),
    path('nuevo_proveedor/', nuevo_proveedor, name='nuevo_proveedor'),
    path('modificarproveedor/<id>/', modificar_proveedor, name="modificar_proveedor"),
    path('eliminarproveedor/<id>/', eliminar_proveedor, name="eliminar_proveedor"),
    #TBK
    path('tbkRes/', statusTrx, name="tbkRes"),
    #Carrito
    path('cart/', cart, name="cart"),
    #usuario
    path('usuario/<id>/', usuario , name='usuario'),
    path('nuevo_usuario/', nuevo_usuario, name='nuevo_usuario'),
    path('listar_usuario/',listar_usuario , name='listar_usuario'),
    path('modificar_usuario/<id>/',modificar_usuario,name='modificar_usuario'),
    path('eliminarusuario/<id>/',eliminar_usuario, name='eliminar_usuario'),
    #Modulos
    path('empleado/',empleado, name='empleado'),
    path('administrador/',administrador, name='administrador'),
    path('proveedor/',provedor, name='provedor'),
    #OrdenCompra
    path('listar_orden/', listar_orden, name='listar_orden' ),
    path('nueva_orden/', nueva_orden, name='nueva_orden'),
    path('modificarorden/<id>/', modificar_orden, name="modificar_orden"),
    path('eliminarorden/<id>/', eliminar_orden, name="eliminar_orden"),
]

core/models.py
from django.db import models
from django.db.models.base import ModelState
from django.db.models.expressions import Case
from django.db.models.fields import BooleanField, CharField, NullBooleanField
from datetime import date,datetime
from proveedor.models import proveedor

#Create your models here
class familia(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class producto(models.Model):
    nombre = models.CharField(max_length=30)
    descripcion = models.TextField(max_length=300)
    precio = models.IntegerField() 
    familia = models.ForeignKey(familia, on_delete=models.PROTECT)
    vencimiento = models.DateField()
    stock = models.IntegerField()
    stock_critico = models.IntegerField()
    proveedor = models.ForeignKey(proveedor, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to='productos', null=True)
    oferta = models.BooleanField(default='0', null=False)

    def __str__(self):
        return self.nombre


opciones_consultas = [

    [0, 'Consulta'],
    [1, 'Reclamo'],
    [2, 'Sugerencia'],
    [3, 'Felicitaciones'],
    [4, 'Solicitud de Proveedor']]

class contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre



class boleta(models.Model):
    fecha = models.DateField(default=datetime.today)
    producto = models.ForeignKey(producto, on_delete=models.CASCADE)
    canitdad_producto = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.id

opciones_estados = [
    [0, 'Pendiente'],
    [1,'Aprobada'],
    [2,'Rechazada'],
]

class ordencompra(models.Model):
    proveedor = models.ForeignKey(proveedor,on_delete=models.CASCADE)
    documento = models.FileField(null=True,blank=True)
    estado = models.BigIntegerField(choices=opciones_estados, null=True, default=0)

    def __str__(self):
        return self.id

core/forms.py
from typing import ClassVar
from django import forms
from django.contrib import auth
from django.db import models
from django.db.models import fields
from django.forms import widgets    
from .models import *
from django.contrib.auth.models import User
from django.forms.widgets import Select


class ContactoForms(forms.ModelForm):
    
    class Meta:
        model = contacto
        #Fiedls detalla todos los datos para el formulario como se necesitan todos se usa __all__
        fields = '__all__'

#widget para fecha de vencimiento de producto


class AgregarProductoForms(forms.ModelForm):
    class Meta:
        model = producto
        fields = '__all__'
        widgets = {
        "vencimiento": forms.SelectDateWidget() 
        }

class AgregarFamiliaForms(forms.ModelForm):
    class Meta:
        model = familia
        fields = '__all__'

class AgregarOrdenForms(forms.ModelForm):
    
    class Meta:
        model = ordencompra
        fields = '__all__'
class ModificarOrdenForms(forms.ModelForm):

    class Meta:
        model = ordencompra
        fields = ('proveedor','documento','estado')
        widgets = {
            'proveedor':Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
                'type':'disabled'

            }),
            'documento':Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
                'type':'disabled'
            }),
            'estado': Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
            })
        }

core/views.py
from factura.models import factura
from usuario.models import Usuario
import carro
from django.contrib.messages.api import success
from django.shortcuts import render, redirect, get_object_or_404
from .models import  *
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.views.decorators.csrf import csrf_exempt
from .services import *
from carro.context_processor import *
from usuario.forms import FormularioUsuario, FormularioUsuarioCompleto,AgregadoAdminForms
from factura.forms import FacturaForm
from boleta.forms import BoletaForm
from boleta.models import boleta
from proveedor.models import proveedor
from proveedor.forms import AgregarProveedorForms
import os
# Create your views here.
#Home de la pagina
def home(request):
    productos = producto.objects.all()
    familias = familia.objects.all()
    try:
        cargo = request.user.cargo
    except:
        cargo = 'Administrador'
    data = {
        'producto': productos,
        'cargo':cargo,
        'familia':familias,
    }
    return render(request, 'core/home.html', data)
#formulario de contacto
def contacto(request):
    data = {
        'form': ContactoForms()
    }
    if request.method == 'POST':
        formulario = ContactoForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "contacto guardado"
        else:
            data["form"] = formulario
    return render(request, 'core/Contacto.html',data)
#Productos
def agregar_producto(request):

    data = {
        'form': AgregarProductoForms()  
    }
    if request.method == 'POST':
        formulario = AgregarProductoForms(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto registrado correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: El producto no fue registrado")

    return render(request, 'core/producto/agregar.html', data)
def listar_productos(request):
    data = {
        'familias':familia.objects.all(),
        'producto':producto.objects.all(),
    }
    return render(request, 'core/producto/listar.html',data)
def modificar_producto(request, id):
    product = get_object_or_404(producto, id=id)
    data = {
        'form': AgregarProductoForms(instance=product)
    }
    if request.method == 'POST':
        formulario = AgregarProductoForms(data=request.POST,instance=product, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Producto modificado correctamente ")
            return redirect(to="listar_producto")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: No se pudo modificar el producto")
    return render(request, 'core/producto/modificar.html', data)
def eliminar_producto(request, id ):
    prod = get_object_or_404(producto, id=id)
    os.remove(os.getcwd()+'\\media\\'+str(prod.imagen))
    prod.delete()
    messages,success(request, "Producto eliminado correctamente")
    return redirect(to="listar_producto")
def nombre_familia(request,familia_id):
    productos = producto.objects.filter(familia_id=familia_id)
    data = { 'producto':productos,'nombre':nombre_familia}
    return render(request,'core/producto/familias.html',data )
#Registro de clientes
def register(request):
    data = {
        'form':FormularioUsuario()
    }
    if request.method == 'POST':
        formulario = FormularioUsuario(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"],password=formulario.cleaned_data["password1"])
            login(request, user)
            print(user)
            messages.success(request, "Registro exitoso")
            return redirect(to="home")
        data['from'] = formulario
    return render(request, 'registration/register.html', data)
#Familias
def listar_familias(request):
    data = {
        'familia':familia.objects.all()
    }
    return render(request, 'core/familia/listar.html', data)
def nueva_familia(request):
    data = {
        'form': AgregarFamiliaForms()  
    }
    if request.method == 'POST':
        formulario = AgregarFamiliaForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Familia registrada correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: La Familia no fue registrada")

    return render(request, 'core/familia/agregar.html', data)
def eliminar_familia(request, id ):
    fam = get_object_or_404(familia, id=id)
    fam.delete()
    messages,success(request, "Familia eliminada correctamente")
    return redirect(to="listar_familias")
def modificar_familia(request, id):
    famil = get_object_or_404(familia, id=id)
    data = {
        'form': AgregarFamiliaForms(instance=famil)
    }
    if request.method == 'POST':
        formulario = AgregarFamiliaForms(data=request.POST,instance=famil)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Familia modificada correctamente ")
            return redirect(to="listar_familias")
        else:
            data["form"] = formulario
            
    return render(request, 'core/familia/modificar.html', data)
#Proveedores 
def listar_proveedor (request):
    prov = proveedor.objects.all()
    data = {
        'proveedor':prov
    }
    return render(request,'core/proveedor/listar.html',data)
def nuevo_proveedor(request):
    data = {
        'form': AgregarProveedorForms()  
    }
    if request.method == 'POST':
        formulario = AgregarProveedorForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Proveedor registrado correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: El proveedor no fue registrado")

    return render(request, 'core/proveedor/agregar.html', data)
def eliminar_proveedor(request, id ):
    prov = get_object_or_404(proveedor, id=id)
    prov.delete()
    messages,success(request, "Proveedor eliminado correctamente")
    return redirect(to="listar_proveedor")
def modificar_proveedor(request, id):
    prov = get_object_or_404(proveedor, id=id)
    data = {
        'form': AgregarProveedorForms(instance=prov)
    }
    if request.method == 'POST':
        formulario = AgregarProveedorForms(data=request.POST,instance=prov)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Proveedor modificado correctamente ")
            return redirect(to="listar_proveedor")
        else:
            data["form"] = formulario
            
    return render(request, 'core/proveedor/modificar.html', data)
#TBK
@csrf_exempt
def statusTrx(request):
    data = {
        'resultado': get_statusTBK(request),
    }
    return render(request, 'core/tbk/statusTbk.html',data)
#Carrito
@csrf_exempt
def cart(request):
    product = producto.objects.all()
    monto = request.POST.get('precio_total')
    data = {
        'producto': product,
        'resultado': get_initTrxTBK(monto),
    }
    return render(request, 'core/carro/cart.html', data)    
#Factura
def nueva_factura(request):
    data = {
        'form':FacturaForm(),
    }
    if request.method == 'POST':
        formulario = FacturaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Factura Registrada correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: la factura no fue registrada")
    return render(request, 'core/factura/agregar.html',data)
def listar_factura(request):
    factur = factura.objects.all()
    data = {
        'factura':factur
    }
    return render(request, 'core/factura/listar.html',data)
def modificar_factura(request,id):
    fact = get_object_or_404(factura, id=id)
    data = {
        'form': FacturaForm(instance=fact)
    }
    if request.method == 'POST':
        formulario = FacturaForm(data=request.POST,instance=fact)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Factura modificada correctamente ")
            return redirect(to="listar_factura")
        else:
            data["form"] = formulario
            
    return render(request, 'core/factura/modificar.html', data)
def eliminar_factura(request,id):
    fact = get_object_or_404(factura, id=id)
    fact.delete()
    messages,success(request, "Factura eliminada correctamente")
    return redirect(to="listar_factura")
#Usuario
def usuario(request,id):
    persona = get_object_or_404(Usuario, id=id)
    data = {
        'form':FormularioUsuario(instance=persona),
    }
    if request.method == 'POST':
        formulario = FormularioUsuario(data=request.POST, instance=persona)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Datos modificados correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: Los datos no fueron actualizados")

    return render(request,'core/persona/modificar.html',data)
def nuevo_usuario(request):
    data = {
        'form':AgregadoAdminForms(),
    }
    if request.method == 'POST':
        formulario = AgregadoAdminForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Usuario Registrado correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: el usuario no fue registrado")

core/templates/core/Contacto.html
{% extends 'core/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

<div class="col-12 col-md-6 offset-md-3 ">
    <div class=" row p-3 mb-2 ">
            <div class="card">
                <div class="card-body">
                    <h2>Contacto</h2>
            
            
                    <form action="" method="POST">
            
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                            &nbsp;
                            <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    
                        </div>
                    
                    </form>
                    {{mensaje}}
            
                </div>
            </div>
        </div>
</div>



{% endblock %}

core/templates/core/base.html
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <title>Ferme</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap" rel="stylesheet">
  <link href="{% static 'css/carro.css' %}" rel="stylesheet" type="text/css">
  <script src="https://use.fontawesome.com/21cb20e192.js"></script>
  {% block head %}
  {% endblock %}
</head>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="/media/admin-interface/logo/logo-fs-web.png" width="60" alt="Logo" />
      FERME</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
        </li>
        {% block nav %}

        {% endblock %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacto' %}">Contáctanos</a>
        </li>
        {% if user.cargo.nombre == 'Empleado' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'empleado' %}">Área Empleados</a>
        </li>
        {% endif %}
        {% if user.cargo.nombre == 'Proveedor' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'provedor' %}">Área Proveedores</a>
        </li>
        {% endif %}
        {% if user.cargo.nombre == 'Administrador' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'administrador' %}">Área Administración</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'usuario' user.id %}">Usuario: {{ user.cargo |title }}</a>
        </li>
        <a class="nav-link d-flex align-items-center" href="{% url 'cart' %}">
          <img id="cart-icon" style="width:20px;" src="{% static 'images/cart.png' %}" alt="carrito" />
          <p id="cart-total" class="float-right">{{importe_cant_carro}}</p>
        </a>  
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
        </li>
        {% endif %}
        <li class="nav-item">
          
        </li>
      </ul>

    </div>
  </nav>
</header>

<body background="/media/admin-interface/logo/fondo.jpg" style="background-repeat: no-repeat; background-size: cover;">
  <div class="cuerpo">
  {% block contenido %}
  {% endblock %}
  </div>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>

  {% block scripts %}
  {% endblock %}




  {% if messages %}
  {% for m in messages %}
  <script>
    Swal.fire(

      "Excelente",
      "{{m}}",
      "success"
    )


  </script>
  {% endfor %}
  {% endif %}
</body>
<footer id="footer fixed-bottom" class="footer-1">
  <div class="main-footer widgets-dark typo-light">
    <div class="container">
      <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="widget subscribe no-box">
            <h5 class="widget-title">Ferme<span></span></h5>
            <p>Juntos construyendo sueños de hogar.</p>
          </div>
        </div>


        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="widget no-box">
            <h5 class="widget-title">Links Rápidos<span></span></h5>
            <ul class="thumbnail-widget">
              <li>
                <div class="thumb-content"><a href="#.">&nbsp;Sobre Nosotros</a></div>
              </li>
              <li>
                <div class="thumb-content"><a href="#.">&nbsp;Términos y Condiciones</a></div>
              </li>
            </ul>
          </div>
        </div>



        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="widget no-box">
            <h5 class="widget-title">Síguenos en nuestras Redes Sociales<span></span></h5>
            <a href="#"> <i class="fa fa-facebook"> </i> </a>
            <a href="#"> <i class="fa fa-twitter"> </i> </a>
            <a href="#"> <i class="fa fa-youtube"> </i> </a>
          </div>
        </div>
        <br>
        <br>


        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="widget no-box">
            <h5 class="widget-title">Contáctanos<span></span></h5>
            <p>Suscribete para recibir nuestras ultimas ofertas, y novedades!</p>
            <div class="emailfield">
              <input type="text" name="email" value="Email">
              <input name="uri" type="hidden" value="arabiantheme">
              <input name="loc" type="hidden" value="en_US">
              <input class="submitbutton ripplelink" type="submit" value="Subscribir">
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="footer-copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <p>Copyright FERME © 2021. Todos los derechos Reservados.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block nav %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    Categorias
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    {% for f in familia %}
    <a class="dropdown-item" href="{% url 'nombre_familia' f.id %}">{{ f.nombre }}</a>
    {% endfor %}
  </div>
</li>
{% endblock %}
{% block contenido %}
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="1" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'css/herramientas.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Respuesta oportuna</h5>
            <p>Entender sus requerimientos
              Aprender de sus experiencias</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'css/herramientass.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Cotizamos tus requerimientos</h5>
            <p>Cotizaciones completas y en tiempo pactado</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'css/herramientasss.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Entrega On Time</h5>
            <p>Recibe tu pedido en tiempo y lugar pactado</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Anterior</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Siguiente</span>
    </a>
  </div>

  <hr>
    <h2 class="text-center">PRODUCTOS RECOMENDADOS</h2>
    <hr>
    <div class="container">
      <div class="row text-center">
        {% for p in producto %}
          {% if p.oferta == 1 %}
          <div class="col-md-4 pb-1 pb-md-0">
            <div class="card" style="background-color: #DADADA;">
              {% if p.imagen %}
              <div>
                <img src="{{ p.imagen.url }}" class="card-img-top" alt="imagen">
              </div>
              {% else %}
              <div>
                <img src="{% static '/images/default.jpg' %}" class="card-img-top" alt="imagen">
              </div>
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ p.nombre }}</h5>
                <p class="card-text">{{ p.descripcion }}</p>
                <p class="card-text">${{ p.precio | intcomma}}</p>
                <a href="{% url 'carro:agregar_home' p.id %}" class="btn btn-primary">Añadir al carrito</a>
              </div>
            </div>        
          </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    
    
{% endblock %}